"""Centralized settings for UZI Web.

Configuration is loaded from two layers:
1. process environment / Docker Compose .env
2. persistent runtime file, defaulting to data/runtime.env

The runtime file lets the Web UI save DingTalk and schedule settings without
committing secrets to the repository.
"""
from __future__ import annotations

import os
from dataclasses import dataclass, field
from functools import lru_cache
from pathlib import Path
from typing import Mapping

ROOT_DIR = Path(__file__).resolve().parents[1]
DEPTHS = {"lite", "medium", "deep"}
RUNTIME_CONFIG_KEYS = [
    "UZI_WEB_PUBLIC_BASE_URL",
    "UZI_WEB_DEFAULT_DEPTH",
    "UZI_WEB_MAX_PARALLEL_JOBS",
    "UZI_WEB_MAX_QUEUE_SIZE",
    "DINGTALK_WEBHOOK_URL",
    "DINGTALK_SECRET",
    "UZI_DINGTALK_NOTIFY_DEFAULT",
    "UZI_SCHEDULE_ENABLED",
    "UZI_SCHEDULE_TIMES",
    "UZI_SCHEDULE_TICKERS",
    "UZI_SCHEDULE_DEPTH",
    "UZI_SCHEDULE_NOTIFY",
]


def _parse_env_file(path: Path) -> dict[str, str]:
    if not path.exists():
        return {}
    values: dict[str, str] = {}
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        key = key.strip()
        value = value.strip()
        if not key:
            continue
        if (value.startswith('"') and value.endswith('"')) or (value.startswith("'") and value.endswith("'")):
            value = value[1:-1]
        values[key] = value
    return values


def _quote_env_value(value: str) -> str:
    if value == "":
        return ""
    if any(ch in value for ch in " \t#\n\r\"'"):
        return '"' + value.replace('\\', '\\\\').replace('"', '\\"') + '"'
    return value


def _initial_data_dir() -> Path:
    return Path(os.getenv("UZI_WEB_DATA_DIR", ROOT_DIR / "data")).resolve()


def _runtime_env_file_path(data_dir: Path | None = None) -> Path:
    configured = os.getenv("UZI_RUNTIME_ENV_FILE")
    if configured:
        return Path(configured).resolve()
    return ((data_dir or _initial_data_dir()) / "runtime.env").resolve()


_RUNTIME_ENV_FILE = _runtime_env_file_path()
_RUNTIME_VALUES = _parse_env_file(_RUNTIME_ENV_FILE)


def _get(name: str, default: str = "") -> str:
    if name in _RUNTIME_VALUES:
        return _RUNTIME_VALUES[name]
    return os.getenv(name, default)


def _bool(name: str, default: bool = False) -> bool:
    value = _get(name, "")
    if value == "":
        return default
    return value.strip().lower() in {"1", "true", "yes", "on"}


def _int(name: str, default: int, minimum: int | None = None) -> int:
    try:
        value = int(_get(name, str(default)))
    except ValueError:
        value = default
    if minimum is not None:
        value = max(minimum, value)
    return value


def _csv(name: str) -> list[str]:
    raw = _get(name, "")
    return [item.strip() for item in raw.replace("，", ",").split(",") if item.strip()]


def _depth(name: str, default: str = "lite") -> str:
    value = _get(name, default).strip().lower()
    return value if value in DEPTHS else default


def save_runtime_config(values: Mapping[str, str | bool | int | None]) -> Path:
    """Persist selected runtime config values to data/runtime.env.

    None means keep the current value. Other values are converted to strings.
    """
    global _RUNTIME_VALUES, _RUNTIME_ENV_FILE

    data_dir = Path(_get("UZI_WEB_DATA_DIR", str(_initial_data_dir()))).resolve()
    data_dir.mkdir(parents=True, exist_ok=True)
    runtime_file = _runtime_env_file_path(data_dir)

    current = _parse_env_file(runtime_file)
    for key, value in values.items():
        if key not in RUNTIME_CONFIG_KEYS or value is None:
            continue
        if isinstance(value, bool):
            current[key] = "true" if value else "false"
        else:
            current[key] = str(value).strip()

    lines = [
        "# UZI Web runtime config",
        "# This file is generated by the Web UI. Do not commit secrets to git.",
    ]
    for key in RUNTIME_CONFIG_KEYS:
        if key in current:
            lines.append(f"{key}={_quote_env_value(current[key])}")
    runtime_file.write_text("\n".join(lines) + "\n", encoding="utf-8")

    _RUNTIME_ENV_FILE = runtime_file
    _RUNTIME_VALUES = _parse_env_file(runtime_file)
    for key, value in _RUNTIME_VALUES.items():
        os.environ[key] = value
    get_settings.cache_clear()
    return runtime_file


@dataclass(frozen=True)
class Settings:
    root_dir: Path = ROOT_DIR
    run_py: Path = ROOT_DIR / "run.py"
    data_dir: Path = field(default_factory=lambda: Path(_get("UZI_WEB_DATA_DIR", ROOT_DIR / "data")).resolve())
    logs_dir: Path = field(default_factory=lambda: Path(_get("UZI_WEB_LOGS_DIR", ROOT_DIR / "logs")).resolve())
    reports_dir: Path = field(default_factory=lambda: Path(_get("UZI_WEB_REPORTS_DIR", ROOT_DIR / "reports")).resolve())
    runtime_env_file: Path = field(default_factory=lambda: _runtime_env_file_path(Path(_get("UZI_WEB_DATA_DIR", ROOT_DIR / "data")).resolve()))

    web_host: str = field(default_factory=lambda: _get("UZI_WEB_HOST", "0.0.0.0"))
    web_port: int = field(default_factory=lambda: _int("UZI_WEB_PORT", 8977, minimum=1))
    public_base_url: str = field(default_factory=lambda: _get("UZI_WEB_PUBLIC_BASE_URL", "").rstrip("/"))

    default_depth: str = field(default_factory=lambda: _depth("UZI_WEB_DEFAULT_DEPTH", "lite"))
    max_parallel_jobs: int = field(default_factory=lambda: _int("UZI_WEB_MAX_PARALLEL_JOBS", 1, minimum=1))
    max_queue_size: int = field(default_factory=lambda: _int("UZI_WEB_MAX_QUEUE_SIZE", 30, minimum=1))
    job_log_tail_chars: int = field(default_factory=lambda: _int("UZI_WEB_JOB_LOG_TAIL_CHARS", 12000, minimum=1000))

    dingtalk_webhook_url: str = field(default_factory=lambda: _get("DINGTALK_WEBHOOK_URL", "").strip())
    dingtalk_secret: str = field(default_factory=lambda: _get("DINGTALK_SECRET", "").strip())
    dingtalk_notify_default: bool = field(default_factory=lambda: _bool("UZI_DINGTALK_NOTIFY_DEFAULT", False))

    schedule_enabled: bool = field(default_factory=lambda: _bool("UZI_SCHEDULE_ENABLED", False))
    schedule_times: list[str] = field(default_factory=lambda: _csv("UZI_SCHEDULE_TIMES"))
    schedule_tickers: list[str] = field(default_factory=lambda: _csv("UZI_SCHEDULE_TICKERS"))
    schedule_depth: str = field(default_factory=lambda: _depth("UZI_SCHEDULE_DEPTH", _depth("UZI_WEB_DEFAULT_DEPTH", "lite")))
    schedule_notify: bool = field(default_factory=lambda: _bool("UZI_SCHEDULE_NOTIFY", True))

    @property
    def job_reports_dir(self) -> Path:
        return self.reports_dir / "jobs"

    def ensure_dirs(self) -> None:
        self.data_dir.mkdir(parents=True, exist_ok=True)
        self.logs_dir.mkdir(parents=True, exist_ok=True)
        self.reports_dir.mkdir(parents=True, exist_ok=True)
        self.job_reports_dir.mkdir(parents=True, exist_ok=True)


@lru_cache(maxsize=1)
def get_settings() -> Settings:
    settings = Settings()
    settings.ensure_dirs()
    return settings
